# Generated by Django 6.0.7 on 2026-07-08 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="License number must have 3 uppercase letters and 5 numbers (Example: ABC12345)",
                        regex="^[A-Z]{3}\\d{5}$",
                    ),
                    django.core.validators.MinLengthValidator(
                        8, message="License number must be 8 symbols"
                    ),
                ],
            ),
        ),
    ]
